$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: train_model
version: 12
type: command

inputs:
  input_url:
    type: uri_folder
outputs:
  output_url:
    type: uri_folder

code: code.py
environment: azureml:env-train-model@latest
command: >
  python code.py
