$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: validate
display_name: validate
version: '5.35'
type: command
inputs:
  input_url:
    type: uri_folder
outputs:
  output_url:
    type: uri_folder
code: code.py
environment: azureml:env-process-data@latest
command: python code.py
