name: Bump Versions

on:
  workflow_run:
    workflows: ["Tests"]  # Must match the 'name:' in check_approvals.yaml
    types: [completed]

permissions:
  contents: write

jobs:
  bump-version:
    # Only run if the PR was merged (not just closed).
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # "base.ref" is the target branch of the PR (e.g., dev or main).
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Bump version
        id: bump_version
        run: |
          if [ -z "${{ github.event.pull_request.labels }}" ]; then
            echo "PR_LABELS is empty or not set. Exiting."
            exit 1
          fi
          python .github/scripts/bump_versions.py
        env:
          PR_LABELS: ${{ toJson(github.event.pull_request.labels) }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}

      - name: Commit changes
        if: ${{ success() }}
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage any changed files (e.g., version.yaml)
          git add .

          # Commit only if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: Bump version after merge (PR #${{ github.event.pull_request.number }})"
            git push origin ${{ github.event.pull_request.base.ref }}
          fi
