name: "Bump Versions"

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [opened]

jobs:
  bump_version:
    runs-on: ubuntu-latest

    env:
      # Extract values from the pull request event payload:
      PR_NUMBER: ${{ github.event.number }}
      PR_LABELS: ${{ toJson(github.event.pull_request.labels) }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      BASE_REF: ${{ github.event.pull_request.base.ref }}
      HEAD_REF: ${{ github.event.pull_request.head.ref }}

    outputs:
      old_version: ${{ steps.get_old_version.outputs.old_version }}
      new_version: ${{ steps.get_new_version.outputs.new_version }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          # Checkout the head branch so commits can be pushed back.
          ref: ${{ env.HEAD_REF }}

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: "Install Dependencies"
        run: |
          pip install pyyaml

      - name: "Get old version"
        id: get_old_version
        run: |
          echo "=== [INFO] Retrieving current global version from version.yaml ==="
          old_version=$(python .github/scripts/bump_version/manage_global_version.py get_version | tail -n 1)
          echo "Current version: $old_version"
          echo "old_version=$old_version" >> $GITHUB_OUTPUT

      - name: "Bump version"
        run: |
          echo "=== [INFO] Bumping global version (if applicable) based on PR labels ==="
          python .github/scripts/bump_version/manage_global_version.py bump

      - name: "Get new version"
        id: get_new_version
        run: |
          echo "=== [INFO] Retrieving new global version ==="
          new_version=$(python .github/scripts/bump_version/manage_global_version.py get_version | tail -n 1)
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: "Bump Azure versions"
        run: |
          echo "=== [INFO] Updating Azure pipeline/component/environment YAMLs with new version ==="
          python .github/scripts/bump_version/manage_azure_versions.py ${{ steps.get_new_version.outputs.new_version }}

      - name: "Commit version bump"
        run: |
          echo "=== [INFO] Committing any version.yaml changes back to branch $HEAD_REF ==="
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .

          # If nothing changed, the commit will fail. Let's ignore that failure gracefully.
          git commit -m "Bump version to ${{ steps.get_new_version.outputs.new_version }} [PR #${{ env.PR_NUMBER }}]" || echo "No changes to commit"

          echo "=== [INFO] Pushing changes to $HEAD_REF ==="
          git push origin $HEAD_REF
