name: Bump Versions

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  bump-version:
    # Only run if the PR was merged (not just closed).
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          # The base ref is the branch into which the PR was merged
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Bump version
        id: bump_version
        run: python .github/scripts/bump_versions.py
        env:
          PR_LABELS: ${{ toJson(github.event.pull_request.labels) }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Commit and push changes
        if: steps.bump_version.outcome == 'success'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.yaml
          git commit -m "Bump version based on PR #${{ env.PR_NUMBER }} labels"
          # Push to the base branch (e.g., 'main') the PR was merged into
          git push origin ${{ env.BASE_REF }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
