# name: Check Approvals

# on:
#   pull_request_review:
#     types: [submitted]
#     branches:
#       - dev
#       - main

# jobs:
#   check_approvals_job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Extract PR Number
#         id: pr_info
#         run: |
#           echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

#       - name: Check Approval Count
#         id: approvals
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const prNumber = process.env.PR_NUMBER;
#             const owner = context.repo.owner;
#             const repo = context.repo.repo;

#             // List all reviews
#             const { data: reviews } = await github.rest.pulls.listReviews({
#               owner,
#               repo,
#               pull_number: prNumber,
#             });

#             // Count how many are 'APPROVED'
#             const approved = reviews.filter(r => r.state === "APPROVED");
#             const approvedCount = approved.length;
#             core.info(`PR #${prNumber} has ${approvedCount} approvals`);

#             // If fewer than 2 approvals, mark the job as failed
#             if (approvedCount < 2) {
#               core.setFailed("Not enough approvals! Need >= 2.");
#             }
