name: CI/CD Pipeline

on:
  pull_request:
    branches: [dev, main]
    types: [opened, reopened, synchronize]

jobs:
  # 1) Lint Job
  lint_job:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Linter
        run: pip install flake8

      - name: Run Lint
        run: flake8 src/

  # 2) Tests Job
  tests_job:
    name: Run Tests
    needs: [lint_job]
    if: ${{ needs.lint_job.result == 'success' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install pytest

      - name: Run Tests
        run: pytest tests/

  # 3) Bump Version Job
  bump_version_job:
    name: Bump Version
    needs: [tests_job]
    if: ${{ needs.tests_job.result == 'success' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install pyyaml

      - name: Bump Version
        run: |
          python .github/scripts/bump_versions.py
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_LABELS: ${{ toJson(github.event.pull_request.labels) }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          BASE_REF: ${{ github.ref }}

      - name: Commit Changes
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: Bump version after merge (PR #${{ github.event.number }})"
            git push origin ${{ github.ref }}
          fi

  # 4) Deploy Job
  deploy_job:
    name: Deploy Pipelines
    needs: [bump_version_job]
    if: ${{ needs.bump_version_job.result == 'success' }}
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP_DEV }}
      AZURE_WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME_DEV }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure via Service Principal
        run: |
          az login --service-principal \
            --username $AZURE_CLIENT_ID \
            --password $AZURE_CLIENT_SECRET \
            --tenant $AZURE_TENANT_ID

      - name: Install Azure ML CLI extension
        run: az extension add -n ml --yes

      - name: Configure defaults
        run: |
          az configure --defaults \
            group=$AZURE_RESOURCE_GROUP \
            workspace=$AZURE_WORKSPACE_NAME \
            subscription=$AZURE_SUBSCRIPTION_ID

      - name: Deploy Environments and Components
        run: |
          for dir in src/train/components/*/; do
            echo "Processing $dir"
            if [ -f "$dir/env.yaml" ]; then
              echo "Deploying environment in $dir"
              az ml environment create --file "$dir/env.yaml"
            else
              echo "No env.yaml found in $dir"
            fi
            if [ -f "$dir/config.yaml" ]; then
              echo "Deploying component in $dir"
              az ml component create --file "$dir/config.yaml"
            else
              echo "No config.yaml found in $dir"
            fi
          done

      - name: Create or Update Pipeline
        run: az ml component create --file src/train/pipeline.yaml

  # 5) Tag & Merge Job
  tag_and_merge_job:
    name: Tag and Merge PR
    needs: [deploy_job]
    if: ${{ needs.deploy_job.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install yq

      - name: Extract PR Info
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Create & Push Tag
        run: |
          VERSION=$(yq e '.version' version.yaml)
          echo "Found version: $VERSION"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v$VERSION" ${{ env.PR_HEAD_SHA }}
          git push origin "v$VERSION"

      - name: Merge Pull Request
        uses: devops-actions/merge-pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ env.PR_NUMBER }}
          merge_method: squash
          commit_title: "Automated Merge after Deployment"
          commit_message: "Merging PR #${{ env.PR_NUMBER }} to target branch"
