name: "CICD Pipeline"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  on_approve:
    uses: ./.github/workflows/on-approve.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  bump_version:
    needs: on_approve
    uses: ./.github/workflows/bump-versions.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
      pr_labels: ${{ toJson(github.event.pull_request.labels) }}
      pr_title: ${{ github.event.pull_request.title }}
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref }}

  deploy:
    needs: bump_version
    uses: ./.github/workflows/deploy-to-azure.yaml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
