name: "CICD Pipeline"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: read
  checks: read

jobs:
  on_approve:
    # Instead of `runs-on: ubuntu-latest` and steps, we directly call the reusable workflow:
    uses: ./.github/workflows/on-approve.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  bump_version:
    needs: on_approve
    uses: ./.github/workflows/bump-versions.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
