name: "CICD Pipeline"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: read
  checks: read

jobs:
  on_approve:
    runs-on: ubuntu-latest
    steps:
      - name: On-Approve
        uses: ./.github/workflows/on-approve.yaml
        with:
          pull_request_number: ${{ github.event.pull_request.number }}

  bump_version:
    runs-on: ubuntu-latest
    needs: on_approve  # Wait until on_approve job completes successfully
    outputs:
      old_version: ${{ steps.call_reusable.outputs.old_version }}
    steps:
      - name: Call Bump-Versions Reusable Workflow
        id: call_reusable
        uses: ./.github/workflows/bump-versions.yaml

        with:
          # If needed
          pull_request_number: ${{ github.event.pull_request.number }}

      - name: Print Old Version
        run: |
          echo "The old version was ${{ steps.call_reusable.outputs.old_version }}"
