name: "CICD Pipeline"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: read
  checks: read

jobs:
  on_approve:
    # Call the On Approve reusable workflow (assumed to be at .github/workflows/on-approve.yaml)
    uses: ./.github/workflows/on-approve.yaml@main
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  bump_version:
    needs: on_approve
    # Call the Bump Versions reusable workflow
    uses: ./.github/workflows/bump-versions.yaml@main
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
      pr_labels: ${{ toJson(github.event.pull_request.labels) }}
      pr_title: ${{ github.event.pull_request.title }}
      base_ref: ${{ github.event.pull_request.base.ref }}
