name: "Deploy pipeline"

on:
  workflow_run:
    workflows: ["PR Checks"]
    types: [completed]

jobs:
  check-approvals:
    # if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check approvals
        id: check
        run: |
          APPROVALS=$(gh pr view ${{ github.event.workflow_run.pull_requests[0].number }} --json reviews --jq '.reviews | map(select(.state == "APPROVED")) | length')
          echo "Number of approvals: $APPROVALS"
          if [ "$APPROVALS" -lt 2 ]; then
            echo "Not enough approvals"
            exit 1
