name: "Merge PR"

on:
  workflow_call:
    inputs:
      pr_number:
        type: number
        required: true
        description: "The pull request number to merge"
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: "Merge the PR"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = parseInt("${{ inputs.pr_number }}", 10);
            console.log(`Merging PR #${prNumber}...`);
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: "merge"  // or 'squash' / 'rebase'
            });
