name: "Merge PR"

on:
  workflow_call:
    inputs:
      pr_number:
        type: number
        required: true
      github_token:
        type: string
        required: true  # <-- Accept it as a normal string input

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: "Merge the PR"
        uses: actions/github-script@v6
        with:
          # Supply the input token here:
          github-token: ${{ inputs.github_token }}
          script: |
            const prNumber = parseInt("${{ inputs.pr_number }}", 10);
            console.log(`Merging PR #${prNumber}...`);
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: "merge"
            });
