name: "MLOps Pipeline"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  on_approve:
    uses: ./.github/workflows/on_approve.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  bump_version:
    needs: on_approve
    uses: ./.github/workflows/bump_version.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
      pr_labels: ${{ toJson(github.event.pull_request.labels) }}
      pr_title: ${{ github.event.pull_request.title }}
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref }}

  deploy:
    needs: bump_version
    uses: ./.github/workflows/push_to_azure.yaml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  roll_back_version:
    name: "Roll Back Version if Deploy Fails"
    needs: deploy
    uses: ./.github/workflows/rollback_version.yaml
    # Only run if the deploy job failed
    if: ${{ failure() }}
    with:
      old_version: ${{ needs.bump_version.outputs.old_version }}
      head_ref: ${{ github.event.pull_request.head.ref }}
    # You can pass additional info if needed, like reason, new_version, etc.
