name: "MLOps Pipeline"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  on_approve:
    name: "On Approve"
    uses: ./.github/workflows/on_approve.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  define_executable_actions:
    name: "Define Executable Actions"
    needs: on_approve
    uses: ./.github/workflows/define_executable_actions.yaml
    with:
      pull_request_labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}

  get_pr_version:
    name: "Get PR Version"
    needs:
      - define_executable_actions
    if: ${{ always() }}
    uses: ./.github/workflows/get_pr_version.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  push_to_azure_dev:
    name: "Push to Azure Dev"
    needs:
      - get_pr_version
      - define_executable_actions
    if: ${{ always() && needs.define_executable_actions.outputs.exec_push_to_azure_dev == 'true' }}
    uses: ./.github/workflows/push_to_azure.yaml
    with:
      MODE: "workspace"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_WORKSPACE_RESOURCE_GROUP: ${{ secrets.AZURE_WORKSPACE_RESOURCE_GROUP }}
      AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
      AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
      AZURE_REGISTRY_LOCATION: ${{ secrets.AZURE_REGISTRY_LOCATION }}

  push_to_azure_shared_registry:
    name: "Push to Azure Shared Registry"
    needs:
      - push_to_azure_dev
      - define_executable_actions
    if: ${{ always() && needs.define_executable_actions.outputs.exec_push_to_azure_shared_registry == 'true' }}
    uses: ./.github/workflows/push_to_azure.yaml
    with:
      MODE: "shared_registry"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_WORKSPACE_RESOURCE_GROUP: ${{ secrets.AZURE_WORKSPACE_RESOURCE_GROUP }}
      AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
      AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
      AZURE_REGISTRY_LOCATION: ${{ secrets.AZURE_REGISTRY_LOCATION }}

  tag_version:
    name: "Tag Version"
    needs:
      - push_to_azure_shared_registry
      - define_executable_actions
      - get_pr_version
    if: ${{ always() && needs.define_executable_actions.outputs.exec_tag_version == 'true' }}
    uses: ./.github/workflows/tag_version.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      pr_version: "${{ needs.get_pr_version.outputs.pr_version }}"
      head_ref: ${{ github.event.pull_request.head.ref }}

  mlops_pipeline_finished:
    name: "MLOps Pipeline Finished"
    needs:
      - tag_version
    runs-on: ubuntu-latest
    steps:
      - name: Echo Pipeline Finished
        run: echo "MLOps pipeline finished"

  merge_pr:
    name: "Merge PR"
    needs: mlops_pipeline_finished
    if: ${{ always() && needs.tag_version.result == 'success' }}
    uses: ./.github/workflows/merge_pr.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      pr_number: ${{ github.event.pull_request.number }}
