name: "MLOps Pipeline"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  on_approve:
    name: "On Approve"
    uses: ./.github/workflows/on_approve.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  get_pr_version:
    name: "Get PR Version"
    needs: on_approve
    uses: ./.github/workflows/get_pr_version.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
    # No job-level outputs block here

  push_to_azure:
    name: "Push to Azure"
    needs: get_pr_version
    uses: ./.github/workflows/push_to_azure.yaml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  tag_version:
    name: "Tag Version"
    needs:
      - push_to_azure
      - get_pr_version
    if: ${{ success() }}
    uses: ./.github/workflows/tag_version.yaml
    # Pass the actual secret token here
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      pr_version: ${{ needs.get_pr_version.outputs.pr_version }}
      head_ref: ${{ github.event.pull_request.head.ref }}

  merge_pr:
    name: "Merge PR"
    needs:
      - tag_version
    if: ${{ success() }}
    uses: ./.github/workflows/merge_pr.yaml
    # Pass the actual secret token here
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      pr_number: ${{ github.event.pull_request.number }}
