name: "MLOps Pipeline"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  on_approve:
    name: "On Approve"
    uses: ./.github/workflows/on_approve.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  get_pr_version:
    name: "Get PR Version"
    needs: on_approve
    uses: ./.github/workflows/get_pr_version.yaml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  push_to_azure_dev:
    name: "Push to Azure Dev"
    needs: get_pr_version
    uses: ./.github/workflows/push_to_azure.yaml
    # The 'with' section is where you can override inputs
    # for the push_to_azure.yaml workflow. For example,
    # if you wanted to force "shared_registry" mode, you'd do:
    # with:
    #   MODE: "shared_registry"
    # But let's default to "workspace" mode for dev:
    with:
      MODE: "workspace"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  tag_version:
    name: "Tag Version"
    needs:
      - push_to_azure_dev
      - get_pr_version
    # Use "if: always()" so this job runs regardless of push_to_azure_dev’s result.
    if: always()
    uses: ./.github/workflows/tag_version.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      pr_version: "${{ format('{0}{1}', needs.get_pr_version.outputs.pr_version, (needs.push_to_azure_dev.result == 'failure' && '-broken' || '')) }}"
      head_ref: ${{ github.event.pull_request.head.ref }}

  merge_pr:
    name: "Merge PR"
    needs:
      - tag_version
    if: ${{ always() && needs.tag_version.result == 'success' }}
    uses: ./.github/workflows/merge_pr.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      pr_number: ${{ github.event.pull_request.number }}
