name: On approve
on:
  pull_request_review:
    types: [submitted]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check approvals
        id: check_approvals
        run: |
          APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '.reviews | map(select(.state == "APPROVED")) | length')
          echo "Number of approvals: $APPROVALS"
          if [ "$APPROVALS" -lt 1 ]; then
            echo "Not enough approvals"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check required checks status
        id: check_checks
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const { data: { check_runs } } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha,
            });

            // Initialize status variables
            let lintCheckPassed = false;
            let repositoryTestsPassed = false;

            // Iterate over check runs to find the ones we're interested in
            for (const check of check_runs) {
              if (check.name === 'Lint Check' && check.conclusion === 'success') {
                lintCheckPassed = true;
              } else if (check.name === 'Repository Tests' && check.conclusion === 'success') {
                repositoryTestsPassed = true;
              }
            }

            if (!lintCheckPassed) {
              core.setFailed('Lint Check did not pass.');
            }

            if (!repositoryTestsPassed) {
              core.setFailed('Repository Tests did not pass.');
            }

            if (lintCheckPassed && repositoryTestsPassed) {
              console.log('All required checks have passed.');
            }
