name: "Push to Azure Dev (using Azure ML SDK, with registry/workspace toggle)"

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
    inputs:
      MODE:
        description: "Deployment mode: 'workspace' or 'shared_registry'"
        required: false
        default: "workspace"

permissions:
  contents: write
  pull-requests: write

jobs:
  push_to_azure:
    name: "Push to Azure"
    runs-on: ubuntu-latest

    env:
      # Mode: either "workspace" or "shared_registry"
      AZURE_MODE: ${{ inputs.MODE }}

      # If workspace mode is used, these are required:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP_DEV }}
      AZURE_WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME_DEV }}

      # If shared_registry mode is used, these are required:
      # Provide them as secrets or variables as appropriate:
      AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
      AZURE_REGISTRY_LOCATION: ${{ secrets.AZURE_REGISTRY_LOCATION }}

      # Azure Service Principal credentials
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: "[INFO] Checkout repository"
        uses: actions/checkout@v3

      - name: "[INFO] Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: "[INFO] Install dependencies"
        run: |
          pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: "[INFO] Push to Azure via Python script"
        run: |
          echo "Deployment mode: $AZURE_MODE"
          python .github/scripts/push_to_azure.py
