name: "Tag Version"

on:
  workflow_call:
    inputs:
      pr_version:
        type: string
        required: true
        description: "The version to tag"
      head_ref:
        type: string
        required: true
        description: "The head branch to check out"
      github_token:
        type: string
        required: true
        description: "GitHub token to authenticate (for pushing tags)"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: "[INFO] Checkout PR branch"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.head_ref }}
          # Pass the token so checkout & pushes are authenticated
          token: ${{ inputs.github_token }}

      - name: "[INFO] Create & Push Git Tag"
        run: |
          VERSION=${{ inputs.pr_version }}
          echo "=== [INFO] Creating tag for version: v${VERSION} ==="

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch --prune --unshallow || true

          git tag -a "v${VERSION}" -m "Tagging version v${VERSION}"
          git push origin "v${VERSION}"
